# Generated by Django 4.2.3 on 2023-07-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateField(auto_now=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_update',
            field=models.DateField(auto_now_add=True, verbose_name='дата последнего изменения'),
        ),
    ]
