# Generated by Django 4.2.3 on 2023-07-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
