# Generated by Django 4.2.3 on 2023-07-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
