# Generated by Django 4.2.3 on 2023-07-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_blog_preview_image_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview_image',
            field=models.ImageField(blank=True, default='content_image/default.jpg', null=True, upload_to='content_image/', verbose_name='изображение (превью)'),
        ),
    ]
