# Generated by Django 4.2.3 on 2023-08-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='product',
            new_name='prod_title',
        ),
    ]
