# Generated by Django 4.2.3 on 2023-08-03 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_product_version_prod_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='prod_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ver', to='main.product', verbose_name='продукт'),
        ),
    ]
