# Generated by Django 4.2.3 on 2023-08-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_author_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('change_prod_description', 'изм.описание'), ('set_is_published', 'снять с публикации'), ('change_category_id', 'изм. категорию')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
