# Generated by Django 4.2.3 on 2023-08-10 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_author_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('change_prod_description', 'can change product description'), ('set_is_published', 'can change status'), ('change_category_id', 'can change category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
